# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: dfrost-a <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/09/11 20:15:59 by dfrost-a          #+#    #+#              #
#    Updated: 2018/09/11 20:20:56 by dfrost-a         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = bsq

SRCS = 

OBJ = 

all: $(NAME)

$(NAME):
		@gcc -Wall -Wextra -Werror -c $(SRCS)
		@gcc $(OBJ) -o $(NAME)

clean:
	/bin/rm -f $(OBJ)

fclean: clean
	/bin/rm -f $(NAME)

re: fclean all
